image: node:12-buster-slim

stages:
  - test

variables:

  #GLOBAL
  IMAGE_NAME: blox-staking-contracts 

  #STAGE
  ACCOUNT_ID_INFRA_STAGE: 121827225315
  AWS_REGION_INFRA_STAGE: "us-west-2"
  DOCKER_REPO_INFRA_STAGE: $ACCOUNT_ID_INFRA_STAGE.dkr.ecr.$AWS_REGION_INFRA_STAGE.amazonaws.com/$IMAGE_NAME
  APP_REPLICAS_INFRA_STAGE: "1"
  ECRLOGIN_INFRA_STAGE: "aws ecr get-login --registry-ids $ACCOUNT_ID_INFRA_STAGE --region $AWS_REGION_INFRA_STAGE --no-include-email"

  #PRODUCTUON
  ACCOUNT_ID_INFRA_PROD: 764289642555
  AWS_REGION_INFRA_PROD: "us-west-2"
  DOCKER_REPO_INFRA_PROD: $ACCOUNT_ID_INFRA_PROD.dkr.ecr.$AWS_REGION_INFRA_PROD.amazonaws.com/$IMAGE_NAME
  APP_REPLICAS_INFRA_PROD: "1"
  ECRLOGIN_INFRA_PROD: "aws ecr get-login --registry-ids $ACCOUNT_ID_INFRA_PROD --region $AWS_REGION_INFRA_PROD --no-include-email"


#blox-infra-stage
Test stage Docker image:
  stage: test
  tags:
    - blox-infra-stage 
  script:
#    - add-apt-repository ppa:ethereum/ethereum -y
#    - apt-get update
#    - apt-get install build-essential -y
#    - apt-get install gcc g++ libssl-dev libudev-dev pkg-config
    - node --version
    - npm install
    - npm install -g --unsafe-perm=true --allow-root ganache-cli truffle
    - set -e
    - ganache-cli --gasLimit 30000000 2> /dev/null 1> /dev/null &
    - sleep 5 # to make sure ganache-cli is up and running before compiling
    - rm -rf build
    - truffle compile
    - truffle migrate --reset --network development
    - truffle test
